modules/icms/controllers/DefaultController.php
<?php

namespace app\modules\icms\controllers;

use app\components\MultiLogin;
use Yii;
use yii\filters\AccessControl;
use app\modules\icms\forms\LoginForm;
use app\components\IcmsHelper;

class DefaultController extends \app\components\controller\Backend
{

    public $layout = 'login';

    public function actions()
    {

        return [
            'error' => [
                'class' => 'app\components\IcmsErrorAction',
                'layout' => Yii::$app->user->isGuest ? 'error' : 'inner'
            ]
        ];
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['index', 'logout', 'dashboard'],
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['?', 'manager'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['dashboard'],
                        'allow' => true,
                        'roles' => ['manager'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        if (\Yii::$app->user->isGuest === false) {
            return $this->redirect(['default/dashboard']);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) === true) {
            $redirectUrl = $model->login();
            if ($redirectUrl !== false) {
                \app\models\user\AuthLog::addLog(\Yii::$app->user->can('developer'));
                Yii::$app->session->setFlash('welcome', Yii::$app->user->identity->first_name);
                return $this->redirect($redirectUrl === false ? ['default/dashboard'] : $redirectUrl);
            }
        }

        return $this->render('index', [
            'model' => $model,
        ]);
    }

    public function actionLost_password()
    {
        if (\Yii::$app->user->isGuest === false) {
            return $this->redirect(['default/dashboard']);
        }
        $model = new \app\modules\icms\forms\LostPasswordForm();
        if ($model->load(Yii::$app->request->post()) === true) {
            $model->changePassword();
            Yii::$app->session->setFlash('success', 'Новый пароль выслан Вам на email');
            return $this->redirect(['default/dashboard']);
        } else {
            return $this->render('lost_password', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        $multiLogin = new MultiLogin();
        $redirectUrl = $multiLogin->goRedirectLogout(['default/index']);
        return $this->redirect($redirectUrl);
    }

    public function actionDashboard()
    {
        $this->layout = 'inner';
        Yii::$app->view->params['breadCrumbs']['crumbs'] = [
            ['title' => \Yii::$app->name],
        ];

        $userLog = \app\models\user\AuthLog::find()
            ->orderBy(['created_at' => SORT_DESC])
            ->limit(11);
        if (Yii::$app->user->can('developer') === false) {
            $userLog->andWhere(['developer_only' => 0]);
        }

        $clear = \Yii::$app->request->post('clear', false);
        if ($clear !== false && Yii::$app->user->can('developer')) {
            switch ($clear) {
                case 'cms':
                    IcmsHelper::deleteCasheFolder(Yii::getAlias('@webroot/icms/assets'));
                    \app\modules\icms\widgets\GreenLine::show('Кеш cms сброшен');
                    break;
                case 'site':
                    IcmsHelper::deleteCasheFolder(Yii::getAlias('@webroot/assets'));
                    \app\modules\icms\widgets\GreenLine::show('Кеш сайта сброшен');
                    break;
                case 'framework':
                    IcmsHelper::deleteCasheFolder(Yii::getAlias('@runtime'));
                    \app\modules\icms\widgets\GreenLine::show('Кеш фрейворка отчищен');
                    break;
                case 'images':
                    IcmsHelper::deleteCasheFiles(Yii::getAlias('@image_cache'));
                    \app\modules\icms\widgets\GreenLine::show('Кеш изображений отчищен');
                    break;
                case 'all':
                    IcmsHelper::deleteCasheFolder(Yii::getAlias('@webroot/icms/assets'));
                    IcmsHelper::deleteCasheFolder(Yii::getAlias('@webroot/assets'));
                    IcmsHelper::deleteCasheFolder(Yii::getAlias('@runtime'));
                    IcmsHelper::deleteCasheFiles(Yii::getAlias('@image_cache'));
                    \app\modules\icms\widgets\GreenLine::show('Весь кеш сброшен');
                    break;
            }
            return $this->refresh();
        }

        $cacheSizes = [
            'cms' => IcmsHelper::getDirecrotySize(Yii::getAlias('@webroot/icms/assets')),
            'site' => IcmsHelper::getDirecrotySize(Yii::getAlias('@webroot/assets')),
            'framework' => IcmsHelper::getDirecrotySize(Yii::getAlias('@runtime')),
        ];

        return $this->render('dashboard', [
            'userLog' => $userLog->all(),
            'baseInfo' => IcmsHelper::getBaseInfo(),
            'cacheSizes' => $cacheSizes,
        ]);
    }

    public function actionPhp_info()
    {
        if (Yii::$app->user->can('developer') === false) {
            return $this->redirect(['default/index']);
        }

        phpinfo();
    }

}

modules/icms/views/layouts/error.php
<?php

use yii\helpers\Html;
use app\modules\icms\assets\IcmsAsset;

IcmsAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title>ICMS<?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
        <?php $this->beginBody() ?>
        <div class='content_wrapper' style="width: 100%">
            <div class='content'>

                <?= $content ?>
                
                <div class='push'></div>
            </div>
            <div class='content_footer'>
                <span>Impresio v<?= Yii::$app->version ?>. Система управления сайтом.</span>
            </div>
        </div>
        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

modules/icms/views/layouts/inner.php
<?php
use app\modules\icms\widgets\AdminMenuDropDown;
use app\modules\icms\widgets\AdminMenuAdvanced;
use app\modules\icms\widgets\BreadCrumbs;
?>

<?php $this->beginContent('@icms/layouts/main.php') ?>

    <div class='header'>
        <?= BreadCrumbs::widget() ?>
        <?= app\modules\icms\widgets\Preloader::widget() ?>
        <div class='btns'>
            <div class='advanced'>
                <?= AdminMenuAdvanced::widget() ?>
            </div>
            <?= AdminMenuDropDown::widget() ?>
        </div>
    </div>
    <?= $content ?>

<?php $this->endContent() ?>

modules/icms/views/layouts/innerPjax.php
<?php
use app\modules\icms\widgets\AdminMenuDropDown;
use app\modules\icms\widgets\AdminMenuAdvanced;
use app\modules\icms\widgets\BreadCrumbs;
use app\components\Pjax;
?>

<?php $this->beginContent('@icms/layouts/main.php') ?>

    <?php Pjax::begin([
        'id' => 'pjax-right',
        'linkSelector' => 'a[data-is-pjax]',
        'options' => ['class' => 'pjax-wraper']
    ]) ?>
        <div class='header'>
            <?= BreadCrumbs::widget() ?>
            <?= app\modules\icms\widgets\Preloader::widget() ?>
            <div class='btns'>
                <div class='advanced'>
                    <?= AdminMenuAdvanced::widget() ?>
                </div>
                <?= AdminMenuDropDown::widget() ?>
            </div>
        </div>
        <?= $content ?>
    <?php Pjax::end() ?>

<?php $this->endContent() ?>

modules/icms/views/layouts/login.php
<?php
use yii\helpers\Html;
use app\modules\icms\assets\IcmsAsset;

/* @var $this \yii\web\View */
/* @var $content string */

$icmsAsset = IcmsAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title>ICMS<?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody();
?>


<?= $content ?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

modules/icms/views/layouts/main.php
<?php

use yii\helpers\Html;
use app\modules\icms\assets\IcmsAsset;
use app\modules\icms\widgets\AdminMenuLeft;
use yii\helpers\Url;

IcmsAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/png" href="/icms/favicon/favicon-16.png" sizes="16x16">
        <link rel="icon" type="image/png" href="/icms/favicon/favicon-32.png" sizes="32x32">
        <link rel="icon" type="image/png" href="/icms/favicon/favicon-64.png" sizes="64x64">
        <link rel="icon" type="image/png" href="/icms/favicon/favicon-128.png" sizes="128x128">
        <?= Html::csrfMetaTags() ?>
        <title>ICMS<?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
        <?php $this->beginBody(); ?>
        <div class="sidebar_wrapper">
            <div class="sidebar">
                <a class="logo" href="/icms" title="Impresio cms v<?= Yii::$app->version ?>">
                    <img src="<?= IcmsAsset::path('img/logo.png') ?>">
                </a>
                <?= AdminMenuLeft::widget() ?>

                <a class="view_site" href="/" target="_blank">Перейти на сайт</a>

            </div>
            <div class="sidebar_footer">
                <div class="subnav_footer">
                    <ul>
                        <li>
                            <a href="<?= Url::to(['users/edit', 'id' => Yii::$app->user->id]) ?>">Редактировать профиль</a>
                        </li>
                        <li>
                            <a href="<?= Url::to(['users/edit_password', 'id' => Yii::$app->user->id]) ?>">Изменить пароль</a>
                        </li>
                        <li>
                            <a href="<?= Url::to(['default/logout']) ?>">Выйти</a>
                        </li>
                    </ul>
                </div>
                <div class="user">
                    <i class="user_settings"></i>
                    <span><?= Yii::$app->user->identity->first_name?:Yii::$app->user->identity->login ?></span>
                </div>
            </div>
        </div>
        <div class="content_wrapper">
            <div class="content">
                <?= \app\modules\icms\widgets\GreenLine::widget() ?>

                <?= $content ?>

                <div class="clear"></div>
                <div class="push"></div>
            </div>
            <div class="content_footer">
                <span>Impresio v<?= Yii::$app->version ?>. Система управления сайтом.</span>
                <?= \app\modules\icms\widgets\DomainSelector::widget() ?>
            </div>
        </div>
        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>